/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AttitudeIcon: typeof import('./src/components/AttitudeIcon.vue')['default']
    CompareDashboard: typeof import('./src/components/CompareDashboard.vue')['default']
    IconPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IconPhArrowRight: typeof import('~icons/ph/arrow-right')['default']
    IconPhCheckCircle: typeof import('~icons/ph/check-circle')['default']
    IconPhCheckCircleFill: typeof import('~icons/ph/check-circle-fill')['default']
    IconPhCircle: typeof import('~icons/ph/circle')['default']
    IconPhClipboardText: typeof import('~icons/ph/clipboard-text')['default']
    IconPhProhibit: typeof import('~icons/ph/prohibit')['default']
    IconPhProhibitInsetFill: typeof import('~icons/ph/prohibit-inset-fill')['default']
    IconPhQuestion: typeof import('~icons/ph/question')['default']
    IconPhQuestionFill: typeof import('~icons/ph/question-fill')['default']
    IconPhStar: typeof import('~icons/ph/star')['default']
    IconPhStarFill: typeof import('~icons/ph/star-fill')['default']
    LiveCodeBar: typeof import('./src/components/LiveCodeBar.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    ModuleCard: typeof import('./src/components/ModuleCard.vue')['default']
    OptionPopover: typeof import('./src/components/OptionPopover.vue')['default']
    QuadStateButton: typeof import('./src/components/QuadStateButton.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
