/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AttitudeIcon: typeof import('./src/components/AttitudeIcon.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    CompareDashboard: typeof import('./src/components/CompareDashboard.vue')['default']
    IconPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IconPhArrowRight: typeof import('~icons/ph/arrow-right')['default']
    IconPhCaretDown: typeof import('~icons/ph/caret-down')['default']
    IconPhCheckCircle: typeof import('~icons/ph/check-circle')['default']
    IconPhCheckCircleFill: typeof import('~icons/ph/check-circle-fill')['default']
    IconPhCircle: typeof import('~icons/ph/circle')['default']
    IconPhClipboardText: typeof import('~icons/ph/clipboard-text')['default']
    IconPhProhibit: typeof import('~icons/ph/prohibit')['default']
    IconPhProhibitInsetFill: typeof import('~icons/ph/prohibit-inset-fill')['default']
    IconPhQuestion: typeof import('~icons/ph/question')['default']
    IconPhQuestionFill: typeof import('~icons/ph/question-fill')['default']
    IconPhStar: typeof import('~icons/ph/star')['default']
    IconPhStarFill: typeof import('~icons/ph/star-fill')['default']
    IPhArrowLeftBold: typeof import('~icons/ph/arrow-left-bold')['default']
    IPhArrowRightBold: typeof import('~icons/ph/arrow-right-bold')['default']
    IPhArrowsLeftRightBold: typeof import('~icons/ph/arrows-left-right-bold')['default']
    IPhChatsCircleBold: typeof import('~icons/ph/chats-circle-bold')['default']
    IPhCheckBold: typeof import('~icons/ph/check-bold')['default']
    IPhCheckCircle: typeof import('~icons/ph/check-circle')['default']
    IPhCheckCircleFill: typeof import('~icons/ph/check-circle-fill')['default']
    IPhFlagCheckeredBold: typeof import('~icons/ph/flag-checkered-bold')['default']
    IPhFloppyDiskBold: typeof import('~icons/ph/floppy-disk-bold')['default']
    IPhFunnelBold: typeof import('~icons/ph/funnel-bold')['default']
    IPhHandshakeBold: typeof import('~icons/ph/handshake-bold')['default']
    IPhLightningFill: typeof import('~icons/ph/lightning-fill')['default']
    IPhProhibit: typeof import('~icons/ph/prohibit')['default']
    IPhProhibitInsetFill: typeof import('~icons/ph/prohibit-inset-fill')['default']
    IPhQuestion: typeof import('~icons/ph/question')['default']
    IPhQuestionBold: typeof import('~icons/ph/question-bold')['default']
    IPhQuestionFill: typeof import('~icons/ph/question-fill')['default']
    IPhStar: typeof import('~icons/ph/star')['default']
    IPhStarFill: typeof import('~icons/ph/star-fill')['default']
    IPhSwordBold: typeof import('~icons/ph/sword-bold')['default']
    IPhXBold: typeof import('~icons/ph/x-bold')['default']
    LiveCodeBar: typeof import('./src/components/LiveCodeBar.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    ModuleCard: typeof import('./src/components/ModuleCard.vue')['default']
    OptionPopover: typeof import('./src/components/OptionPopover.vue')['default']
    QuadStateButton: typeof import('./src/components/QuadStateButton.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
